### ISSUE TITLE
当使用 Arm64 版本的时候，出现 exec /entrypoint: exec format error 错误

### ISSUE THREAD

**Issue by EvanNotFound** [Apocalypsor/dujiaoka-docker#10]
我的部分 `docker-compose.yml`：

```yaml
version: "3"

services:
  faka:
    # image: ghcr.io/apocalypsor/dujiaoka:latest
    # 国内服务器可以用 hkccr.ccs.tencentyun.com/apocalypsor/dujiaoka:latest
    image: ghcr.io/apocalypsor/dujiaoka:arm
    container_name: faka
    environment:
        - INSTALL=false
        # - INSTALL=true
        # - MODIFY=true
    volumes:
      - ./env.conf:/dujiaoka/.env
      - ./uploads:/dujiaoka/public/uploads
      - ./storage:/dujiaoka/storage
      - ./favicon.ico:/dujiaoka/public/favicon.ico:ro
      - ./favicon.ico:/dujiaoka/public/assets/style/favicon.ico:ro
      - ./default.png:/dujiaoka/public/assets/common/images/default.jpg:ro
```

报错日志内容：

```shell
➜  dujiaoka sudo docker compose up  
[+] Running 3/0
 ✔ Container faka-redis  Created                                              0.0s 
 ✔ Container faka-data   Created                                              0.0s 
 ✔ Container faka        Recreated                                            0.1s 
Attaching to faka, faka-data, faka-redis
faka-redis  | 1:C 09 Mar 2024 17:51:52.845 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
faka-redis  | 1:C 09 Mar 2024 17:51:52.847 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
faka-redis  | 1:C 09 Mar 2024 17:51:52.847 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
faka-redis  | 1:C 09 Mar 2024 17:51:52.847 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
faka-redis  | 1:M 09 Mar 2024 17:51:52.848 * monotonic clock: POSIX clock_gettime
faka-redis  | 1:M 09 Mar 2024 17:51:52.848 * Running mode=standalone, port=6379.
faka-redis  | 1:M 09 Mar 2024 17:51:52.849 * Server initialized
faka-redis  | 1:M 09 Mar 2024 17:51:52.849 * Loading RDB produced by version 7.2.4
faka-redis  | 1:M 09 Mar 2024 17:51:52.849 * RDB age 44 seconds
faka-redis  | 1:M 09 Mar 2024 17:51:52.849 * RDB memory usage when created 0.86 Mb
faka-redis  | 1:M 09 Mar 2024 17:51:52.849 * Done loading RDB, keys loaded: 2, keys expired: 0.
faka-redis  | 1:M 09 Mar 2024 17:51:52.850 * DB loaded from disk: 0.001 seconds
faka-redis  | 1:M 09 Mar 2024 17:51:52.850 * Ready to accept connections tcp
faka-data   | 2024-03-09 17:51:52+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.7.3+maria~focal started.
faka        | exec /entrypoint: exec format error
faka-data   | 2024-03-09 17:51:53+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
faka-data   | 2024-03-09 17:51:53+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.7.3+maria~focal started.
faka-data   | 2024-03-09 17:51:53+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
faka-data   | 2024-03-09 17:51:53 0 [Note] mariadbd (server 10.7.3-MariaDB-1:10.7.3+maria~focal) starting as process 1 ...
faka-data   | 2024-03-09 17:51:53 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
faka-data   | 2024-03-09 17:51:53 0 [Note] InnoDB: Number of transaction pools: 1
faka-data   | 2024-03-09 17:51:53 0 [Note] InnoDB: Using ARMv8 crc32 + pmull instructions
faka-data   | 2024-03-09 17:51:53 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
faka-data   | 2024-03-09 17:51:53 0 [Note] InnoDB: Using Linux native AIO
faka-data   | 2024-03-09 17:51:53 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
faka-data   | 2024-03-09 17:51:53 0 [Note] InnoDB: Completed initialization of buffer pool
faka exited with code 0
faka-data   | 2024-03-09 17:51:53 0 [Note] InnoDB: 128 rollback segments are active.
faka-data   | 2024-03-09 17:51:53 0 [Note] InnoDB: Creating shared tablespace for temporary tables
faka-data   | 2024-03-09 17:51:53 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
faka-data   | 2024-03-09 17:51:53 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
faka-data   | 2024-03-09 17:51:53 0 [Note] InnoDB: 10.7.3 started; log sequence number 2836692; transaction id 4276
faka-data   | 2024-03-09 17:51:53 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
faka-data   | 2024-03-09 17:51:53 0 [Note] Plugin 'FEEDBACK' is disabled.
faka-data   | 2024-03-09 17:51:53 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
faka-data   | 2024-03-09 17:51:53 0 [Note] Server socket created on IP: '0.0.0.0'.
faka-data   | 2024-03-09 17:51:53 0 [Note] Server socket created on IP: '::'.
faka-data   | 2024-03-09 17:51:53 0 [Note] mariadbd: ready for connections.
faka-data   | Version: '10.7.3-MariaDB-1:10.7.3+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
faka-data   | 2024-03-09 17:51:53 0 [Note] InnoDB: Buffer pool(s) load completed at 240309 17:51:53
faka exited with code 1
faka exited with code 1
faka exited with code 1
faka exited with code 1
```

我的服务器架构：

```shell
➜  dujiaoka uname -a        
Linux instance-20231211-2000 5.15.0-1049-oracle #55-Ubuntu SMP Mon Nov 20 19:53:49 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```
