### ISSUE TITLE
HTTP 500 ERROR!

### ISSUE THREAD

**Issue by piwawa** [Apocalypsor/dujiaoka-docker#14]
```
env.conf

APP_NAME=test
APP_ENV=local
APP_KEY=fea8f4w84g51dw5a
APP_DEBUG=false
APP_URL=https://xxxxt.www
#ADMIN_HTTPS=true

LOG_CHANNEL=stack

# 数据库配置
DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=dujiaoka
DB_USERNAME=dujiaoka
DB_PASSWORD=wdawd845

# redis配置
REDIS_HOST=redis
REDIS_PASSWORD=
REDIS_PORT=6379

BROADCAST_DRIVER=log
SESSION_DRIVER=file
SESSION_LIFETIME=120


# 缓存配置
# file为磁盘文件  redis为内存级别
# redis为内存需要安装好redis服务端并配置
CACHE_DRIVER=redis

# 异步消息队列
# sync为同步  redis为异步
# 使用redis异步需要安装好redis服务端并配置
QUEUE_CONNECTION=redis

# 后台语言
## zh_CN 简体中文
## zh_TW 繁体中文
## en    英文
DUJIAO_ADMIN_LANGUAGE=zh_CN

# 后台登录地址
ADMIN_ROUTE_PREFIX=/admin
```

```
docker compose.conf

version: "3"

services:
  faka:
    image: ghcr.io/apocalypsor/dujiaoka:latest
    # 国内服务器可以用: hkccr.ccs.tencentyun.com/apocalypsor/dujiaoka:latest
    container_name: faka
    environment:
        - INSTALL=false
        # - INSTALL=true
    volumes:
      - ./env.conf:/dujiaoka/.env
      - ./uploads:/dujiaoka/public/uploads
      - ./storage:/dujiaoka/storage
    ports:
      - 127.0.0.1:14752:80
    restart: always
 
  db:
    image: mariadb:focal
    container_name: faka-data
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Bodwadw
      - MYSQL_DATABASE=dujiaoka
      - MYSQL_USER=dujiaoka
      - MYSQL_PASSWORD=wdawd845
    volumes:
      - ./data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: faka-redis
    restart: always
    volumes:
      - ./redis:/data

```

每次用域名访问就报这个错：
![image](https://github.com/Apocalypsor/dujiaoka-docker/assets/46926496/3ac379cd-77a9-4079-b0dc-93a7bf43b301)

本地ip+端口就会这样：
```
faka        | 172.22.0.1 - - [07/Jul/2024:10:21:05 +0000] "GET / HTTP/1.1" 500 1570 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
faka        | 172.22.0.1 - - [07/Jul/2024:10:21:07 +0000] "GET / HTTP/1.1" 500 1570 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
```

用的 Arm 服务器，部署过程没报错，就是完全访问不了，域名已修改。
